# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6343444e1827d030ebc58fb4de0a75d11ae02bba65f98fe686d2e41c196edcc2884d8c6a35346f12eb804cfef8d65e8733a70b2f216e8cc32dad9509b627bc4

test:
  secret_key_base: 6fea45ec21d867435835c5b428a9dfbf758338e99feda9546e388ee13c745defbe95109006902d519249e59227264cdfe0d2d8b1ca0e7b6a73fbb07365a04787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
